In [1]:
import time
from tensorflow.keras.models import load_model

In [2]:
import tensorflow.keras as tfk
import tensorflow as tf
from tensorflow.keras.saving import register_keras_serializable


@register_keras_serializable()
class MyModel(tfk.Model):
    def __init__(self,**kwargs):
        super().__init__()
        # Define layers only, do not pass data
        self.conv = tfk.layers.Conv2D(5, (3, 3), activation='relu')
        self.maxpool = tfk.layers.MaxPooling2D((2, 2))
        self.flatten = tfk.layers.Flatten()
        self.dense1 = tfk.layers.Dense(128, activation='relu')
        self.dense2 = tfk.layers.Dense(256, activation='relu')
        self.dropout=tfk.layers.Dropout(0.2)
        self.dense3 = tfk.layers.Dense(128, activation='relu')
        self.dense4 = tfk.layers.Dense(10, activation='sigmoid')
        self.out = tfk.layers.Dense(1, activation='sigmoid')

    def call(self, inputs,training=False):
        x = self.conv(inputs)
        x = self.maxpool(x)
        x = self.flatten(x)
        x = self.dense1(x)
        x = self.dense2(x)
        if training==True:
            x=self.dropout(x)
            print('used dropout')
        else:
            pass 
        x = self.dense3(x)
        x = self.dense4(x)
        return self.out(x)


In [3]:
model = MyModel()

# Dummy input: batch of 8 images, 28x28 grayscale
x = tf.random.normal([ 10,28, 28, 1])

# Forward pass
out = model(x,training=False)
print(out.shape)  # Should be (8, 1)


(10, 1)


In [4]:
model.call(x,training=False)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.5784798 ],
       [0.55458504],
       [0.559776  ],
       [0.5312792 ],
       [0.55788535],
       [0.55140775],
       [0.6024995 ],
       [0.59167135],
       [0.5583817 ],
       [0.54601955]], dtype=float32)>

In [5]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy','precision','recall'])

In [6]:
import numpy as np

In [7]:
y=np.random.choice([0 ,1], size=10)

In [8]:
start=time.time()

In [9]:
model.fit(x, y, epochs=100)

Epoch 1/100
used dropout
used dropout
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.6919 - precision: 0.5000 - recall: 1.0000
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6000 - loss: 0.6493 - precision: 0.5556 - recall: 1.0000
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8000 - loss: 0.6182 - precision: 0.7143 - recall: 1.0000
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5320 - precision: 1.0000 - recall: 1.0000
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5083 - precision: 1.0000 - recall: 1.0000
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.4604 - precision: 1.0000 - recall: 1.0000
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.3682 - precision: 1.0000 - recall: 1.0000
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.3109 - precision: 1.0000 - recall: 1.0000
Epoch 9/

In [10]:
test=tf.random.normal([1,28,28,1],seed=2)

In [11]:
print(test)

tf.Tensor(
[[[[-8.58110845e-01]
   [-1.96622983e-01]
   [ 1.38950452e-01]
   [-1.22127676e+00]
   [-4.03412849e-01]
   [-1.14540410e+00]
   [ 6.39824033e-01]
   [-1.57661188e+00]
   [-1.02601063e+00]
   [ 6.28508329e-01]
   [-8.28223765e-01]
   [ 3.46677154e-01]
   [ 1.39865935e+00]
   [ 1.07179785e+00]
   [ 1.22293270e+00]
   [-7.28901625e-02]
   [ 4.16036010e-01]
   [ 5.97756982e-01]
   [ 6.33795202e-01]
   [ 4.17726129e-01]
   [ 8.26247931e-01]
   [-1.16132021e+00]
   [ 8.44961941e-01]
   [-8.92679870e-01]
   [ 1.35161734e+00]
   [ 1.21505463e+00]
   [-9.55166757e-01]
   [ 3.83196399e-02]]

  [[-3.90533805e-02]
   [-1.35383523e+00]
   [-2.45376420e+00]
   [-4.94711846e-01]
   [ 1.20521830e-02]
   [ 3.00712854e-01]
   [-1.40088725e+00]
   [ 8.18691373e-01]
   [-9.49368298e-01]
   [ 1.30835330e+00]
   [-2.04252195e+00]
   [-1.13588095e+00]
   [-7.66330719e-01]
   [-6.42016411e-01]
   [-1.50162101e+00]
   [ 1.59372497e+00]
   [-1.85446382e+00]
   [-9.36664820e-01]
   [-5.27155578e-01]


In [12]:
model.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step


array([[0.37767094]], dtype=float32)

In [13]:
model.summary()

Model: "my_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (10, 26, 26, 5)             │              50 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (10, 845)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (10, 128)                   │         108,288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (10, 256)                   │          33,024 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (10, 128)                   │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (10, 10)                    │           1,290 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (10, 1)                     │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 526,679 (2.01 MB)

 Trainable params: 175,559 (685.78 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 351,120 (1.34 MB)

In [14]:
model.save(r"C:\Users\varad\saved_model.keras")

In [15]:
model_imported=load_model(r"C:\Users\varad\saved_model.keras")

In [16]:
test=tf.random.normal([1,28,28,1],seed=2)

In [17]:
print(test)

tf.Tensor(
[[[[-4.45977837e-01]
   [-6.99256301e-01]
   [ 2.50438261e+00]
   [-2.53216892e-01]
   [ 7.09692359e-01]
   [ 1.14621794e+00]
   [ 5.37063718e-01]
   [-2.18624964e-01]
   [ 3.50900680e-01]
   [ 1.59204674e+00]
   [-1.10274088e+00]
   [-1.67137489e-01]
   [-6.38491139e-02]
   [ 2.66634017e-01]
   [-1.41766179e+00]
   [-1.51401114e+00]
   [ 7.26063550e-02]
   [-6.66490555e-01]
   [-2.10361290e+00]
   [ 1.10899079e+00]
   [-1.01120627e+00]
   [ 5.12360036e-01]
   [-1.65748334e+00]
   [-4.11509722e-01]
   [-1.33286345e+00]
   [ 6.69026494e-01]
   [ 9.10176814e-01]
   [ 1.25765073e+00]]

  [[ 8.94572496e-01]
   [-6.01801634e-01]
   [ 8.73714924e-01]
   [ 5.92275187e-02]
   [-1.49341261e+00]
   [-4.56158072e-01]
   [-1.78395951e+00]
   [ 2.46001348e-01]
   [ 1.49860215e+00]
   [-9.19485509e-01]
   [-1.11875796e+00]
   [ 2.07797480e+00]
   [ 3.74981970e-01]
   [-5.38360476e-01]
   [-5.80331311e-02]
   [-5.31203598e-02]
   [-1.24238610e+00]
   [ 1.22026160e-01]
   [-5.01974821e-01]


In [18]:
model_imported.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([[0.8822444]], dtype=float32)