COFFEE ROASTING PROBLEM

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import math
import tensorflow as tf
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

In [37]:
x=np.array([[200.0,17.0]])

In [38]:
layer_1=Dense(units=3,activation='sigmoid')

In [39]:
a1=layer_1(x)

In [40]:
a1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 1.]], dtype=float32)>

In [41]:
layer_2=Dense(units=1,activation='sigmoid')

In [42]:
a2=layer_2(a1)  #two layeres

In [43]:
a2

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.41727826]], dtype=float32)>

In [44]:
def threshold(a2):
    if a2[0][0]>=0.5:
        return 1
    else: return 0

In [45]:
threshold(a2)

0

In [46]:
model=Sequential([layer_1,layer_2])

In [47]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (1, 3)                      │               9 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (1, 1)                      │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

In [48]:
x=np.array([[200.0,17.0],
           [120.0,5.0],
           [425.0,20.],
           [212.0,18.0]])

In [49]:
y=np.array([1,0,0,1])

In [50]:
model.get_layer('dense').get_weights()     #set by tensorfolow by itself based on input dimensions

ValueError: No such layer: dense. Existing layers are: ['dense_2', 'dense_3'].

In [51]:
model.get_layer('dense_1').get_weights()         #set by tensorfolow by itself based on input dimensions

ValueError: No such layer: dense_1. Existing layers are: ['dense_2', 'dense_3'].

In [52]:
#compiling

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01)
)

model.fit(x,y,epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 501ms/step - loss: 0.7070
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.7054
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.7039
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.7025
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.7012
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.7000
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.6989
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.6979
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.6971
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.6963


In [33]:
model.get_layer('dense').get_weights()

[array([[-0.423841  , -0.6892797 ,  0.09828621],
        [-0.44889444,  0.6263679 ,  0.30399388]], dtype=float32),
 array([-1.4727704e-20,  0.0000000e+00, -5.0464779e-04], dtype=float32)]

In [34]:
model.get_layer('dense_1').get_weights()

[array([[ 0.15993619],
        [-1.0931078 ],
        [ 0.37162483]], dtype=float32),
 array([-0.09809364], dtype=float32)]

In [35]:
#predict for a testing data

model.predict(np.array([[330,16]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[0.56795955]], dtype=float32)