In [17]:
def knapsack(sum,wei,vals,n):
    if n==0:
        return 0
    elif sum==0:
        return 0
    else:
        if wei[n-1]<=sum:
            option1= vals[n]+ knapsack(sum-wei[n-1],wei,vals,n-1)
            option2= knapsack(sum,wei,vals,n-1)
            res= max(option1,option2)
        else:
            res= knapsack(sum,wei,vals,n-1)
        return res

In [18]:
wei=[4,6,3,5,2]
vals=[10,20,12,18,8]

In [19]:
knapsack(15,wei,vals,4)

50

# Onehot encoder

In [20]:
arr=['b','c','d']

In [21]:
en=enumerate(sorted(set(arr)))

In [22]:
for x in en:
    print(x)
    print(x[0])

(0, 'b')
0
(1, 'c')
1
(2, 'd')
2


In [23]:
import numpy as np

In [24]:
encoder=[]

In [25]:
for i,j in en:
    one=[0]*(len(arr))
    one[i]=1
    encoder.append(one)

In [26]:
encoder

[]

In [33]:
import numpy as np

arr = ['b', 'c', 'd','c','d','a','g','t']
classes = sorted(set(arr))  # ['b', 'c', 'd']
encoder = []

for i, val in enumerate(classes):
    one = np.zeros(len(classes))
    one[i] = 1
    encoder.append(one)

In [34]:
encoder

[array([1., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 1.])]

In [35]:
np.array(encoder)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
classes

['a', 'b', 'c', 'd', 'g', 't']

In [38]:
for x in enumerate(classes):
    print(x)

(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')
(4, 'g')
(5, 't')


# Label ENcoder

In [39]:
ordinal=['low','medium','high','low','high','medium']

In [40]:
labels={'low':0,'medium':1,'high':2}

In [42]:
label_encoder=[]

In [43]:
no_classes=len(labels)

In [45]:
no_classes

3

In [47]:
for x in ordinal:
    ordinal[ordinal.index(x)]=labels[x]

In [48]:
ordinal

[0, 1, 2, 0, 2, 1]

# High cardinality target encoding using mean

In [49]:
import pandas as pd
import numpy as np

# Simulate high-cardinality data
n = 10_000_000
categories = [f"id_{i}" for i in range(100_000)]  # 100k unique values

df = pd.DataFrame({
    'cat': np.random.choice(categories, size=n),
    'target': np.random.randint(0, 2, size=n)
})

# Fast, vectorized target encoding
means = df.groupby('cat')['target'].mean()
df['encoded'] = df['cat'].map(means)


In [50]:
means

cat
id_0        0.582524
id_1        0.416667
id_10       0.516484
id_100      0.486486
id_1000     0.463158
              ...   
id_99995    0.463636
id_99996    0.527778
id_99997    0.477778
id_99998    0.579439
id_99999    0.370370
Name: target, Length: 100000, dtype: float64

# hash encoding

In [65]:
city = 'SanFrancisco'
hash_val = hash(city)   # Maps to bucket 0–99


In [66]:
hash_val

-1850309022097977199

# TF IDF Encoding

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()
X = vec.fit_transform(["the cat sat", "the dog sat"])

# 3. 📦 Word Embeddings (e.g., Word2Vec, GloVe)

In [74]:
from gensim.models import Word2Vec
model = Word2Vec([['the', 'cat', 'sat']], vector_size=100)
embedding = model.wv['cat']

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

# 🤖 Transformer Embeddings (BERT, GPT)


In [75]:
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

C:\Users\varad\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\varad\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [76]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

# Bag of Words

In [94]:
reviews=['the movie is so horrible that I could barely finish its first half','the movie is so great that I recommended to all']

In [95]:
bag_of_words=list()

In [96]:
for review in reviews:
    for x in review.split():
        if x not in bag_of_words:
            bag_of_words.append(x)

In [97]:
bag_of_words

['the',
 'movie',
 'is',
 'so',
 'horrible',
 'that',
 'I',
 'could',
 'barely',
 'finish',
 'its',
 'first',
 'half',
 'great',
 'recommended',
 'to',
 'all']

In [100]:
for review in reviews:
    encoder=np.zeros(len(bag_of_words))
    for y in review.split():
        if y in bag_of_words:
            index=bag_of_words.index(y)
            encoder[index]=1
        else:pass
    
    print(encoder)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
[1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
