In [8]:
2+3

5

In [9]:
6+3

9

<p style="font-size:28px;">Tensorflow sequential model with compile function</p>

In [10]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras import Sequential 
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

In [11]:
x=np.array([[200.0,17.0],
           [120.0,5.0],
           [425.0,20.],
           [212.0,18.0]])

In [12]:
y=np.array([1,0,0,1])

In [13]:
x= (x - np.mean(x, axis=0)) / np.std(x, axis=0)

In [14]:
x

array([[-0.34758084,  0.34050261],
       [-1.05602587, -1.70251306],
       [ 1.6449208 ,  0.85125653],
       [-0.24131409,  0.51075392]])

In [15]:
layer_1=Dense(units=2,name='L1',activation='sigmoid')

In [16]:
a1=layer_1(x)

In [17]:
layer_2=Dense(units=1,name='L2',activation='sigmoid')

In [18]:
a2=layer_2(a1)

In [19]:
# tensor flow assumes parameters

model=Sequential([layer_1,layer_2])

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ L1 (Dense)                           │ (4, 2)                      │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ L2 (Dense)                           │ (4, 1)                      │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.get_layer('L1').get_weights()

[array([[0.33706164, 1.201986  ],
        [0.56773114, 0.8084115 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [22]:
model.get_layer('L2').get_weights()

[array([[-0.6502274],
        [-1.2074105]], dtype=float32),
 array([0.], dtype=float32)]

In [23]:
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01)
)

In [24]:
model.fit(x,y,epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 796ms/step - loss: 0.8315
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.8240
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.8167
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.8096
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.8027
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.7959
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.7894
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.7830
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.7769
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.7709
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.7651
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.7596
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.7542
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.7490
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.7441
Epo

In [25]:
model.get_weights()

[array([[ 4.221719 ,  3.9629884],
        [-4.313978 , -4.090716 ]], dtype=float32),
 array([-0.41173527, -0.45086288], dtype=float32),
 array([[-4.499175],
        [-5.131031]], dtype=float32),
 array([4.22878], dtype=float32)]

In [26]:
model.predict(np.array([[-0.34758084,  0.34050261]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step


array([[0.9797489]], dtype=float32)

In [27]:
model.predict(np.array([[-1.05602587, -1.70251306]]))
       

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[0.00998633]], dtype=float32)

In [28]:
model.predict(np.array([[ 1.6449208 ,  0.85125653]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[0.00817637]], dtype=float32)

In [29]:
model.predict(np.array([[-0.24131409,  0.51075392]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[0.9813318]], dtype=float32)

## forward propagation   

In [30]:
def sigmoid(z):
    return (1/(1+np.exp(-z)))

In [31]:
def dense(a_in,w,b):
    units=w.shape[1]
    a_out=np.zeros(units)
    for i in range(units):
        z=np.dot(w[:,i],a_in)+b[i]
        a_out[i]=sigmoid(z)
    return a_out

In [32]:
def sequential(x,w1,b1,w2,b2):
    a_1=dense(x,w1,b1)
    a_2=dense(a_1,w2,b2)
    return a_2

In [33]:
def predict(x,w1,b1,w2,b2):
    res=sequential(x,w1,b1,w2,b2)
    if res>=0.5:
        return 1
    else:
        return 0

In [34]:
w1=np.array([[ 3.9579391, -4.034256 ],
        [-4.0585375,  4.3953776]])

b1=np.array([ 0.01341179, -0.00776744])

In [35]:
w2=np.array([[-6.2692986],
        [ 3.6812208]])

b2=np.array([1.315409])

In [36]:
predict(x[0],w1,b1,w2,b2)

1

In [37]:
predict(x[1],w1,b1,w2,b2)

0

In [38]:
predict(x[2],w1,b1,w2,b2)

0

In [39]:
predict(x[3],w1,b1,w2,b2)

1

<p style="font-size:30px;">Using Vectorization</p>

In [43]:
def dense_vectorized(x,W,b):
    res= np.matmul(x,W)+b
    return sigmoid(-res)

In [44]:
def sequential_vectorization(x,W1,b1,W2,b2):
    a1=dense_vectorized(x,W1,b1)
    a2=dense_vectorized(a1,W2,b2)
    return a2

In [45]:
sequential_vectorization(x[0],w1,b1,w2,b2)

array([0.98764823])

In [46]:
sequential_vectorization(x[1],w1,b1,w2,b2)

array([0.01123291])

In [47]:
sequential_vectorization(x[2],w1,b1,w2,b2)

array([0.01070086])

In [48]:
sequential_vectorization(x[3],w1,b1,w2,b2)

array([0.98920664])