In [333]:
import numpy as np
import math
import tensorflow as tf
from tensorflow.keras.layers import Normalization

In [334]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [335]:
def dense(a_in,W,b):
    units=W.shape[1]
    a_out=np.zeros(units)
    for i in range(units):
        w=W[:,i]
        z= np.dot(w,a_in)+b[i]
        a_out[i]=sigmoid(z)
    return a_out

In [336]:
def Sequential(x,W1,b1,W2,b2):
    a1=dense(x,W1,b1)
    a2=dense(a1,W2,b2)
    return a2

In [337]:
x=np.array([[200.0,17.0],
           [120.0,5.0],
           [425.0,20.],
           [212.0,18.0]])

In [338]:
#normalizing first feature
y=np.array([1,0,0,1])

In [339]:
W1=np.array([[-0.8128951 ,  0.58167994, -0.6926838 ],
        [-0.28268427,  0.8392546 , -0.3195731 ]])

In [340]:
b1=np.array( [0., 0., 0.])

In [341]:
W2=np.array([[ 1.028956 ],
        [-1.1769795],
        [-0.7182141]])
b2=np.array([0.])

In [346]:
x_norm = (x - np.mean(x, axis=0)) / np.std(x, axis=0)


In [347]:
Sequential(x_norm[0],W1,b1,W2,b2)

array([0.39327329])

In [348]:
Sequential(x_norm[1],W1,b1,W2,b2)

array([0.52969143])

In [350]:
Sequential(x_norm[2],W1,b1,W2,b2)

array([0.27779578])

In [351]:
Sequential(x_norm[3],W1,b1,W2,b2)

array([0.37642475])

In [352]:
Sequential([200.0,17.0],W1,b1,W2,b2)

array([0.23559572])