In [87]:
2+3

5

In [88]:
6+3

9

###### 

In [89]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras import Sequential 
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

In [90]:
x=np.array([[200.0,17.0],
           [120.0,5.0],
           [425.0,20.],
           [212.0,18.0]])

In [91]:
y=np.array([1,0,0,1])

In [92]:
x= (x - np.mean(x, axis=0)) / np.std(x, axis=0)

In [93]:
x

array([[-0.34758084,  0.34050261],
       [-1.05602587, -1.70251306],
       [ 1.6449208 ,  0.85125653],
       [-0.24131409,  0.51075392]])

In [94]:
layer_1=Dense(units=2,name='L1',activation='sigmoid')

In [95]:
a1=layer_1(x)

In [96]:
layer_2=Dense(units=1,name='L2',activation='sigmoid')

In [97]:
a2=layer_2(a1)

In [98]:
# tensor flow assumes parameters

model=Sequential([layer_1,layer_2])

In [99]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ L1 (Dense)                           │ (4, 2)                      │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ L2 (Dense)                           │ (4, 1)                      │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [100]:
model.get_layer('L1').get_weights()

[array([[ 1.0962771 , -1.0655746 ],
        [-0.52925235, -0.21772623]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [101]:
model.get_layer('L2').get_weights()

[array([[0.8918148],
        [0.4601711]], dtype=float32),
 array([0.], dtype=float32)]

In [102]:
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01)
)

In [ ]:
model.fit(x,y,epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 508ms/step - loss: 0.7957
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.7909
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.7862
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.7816
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.7771
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.7728
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.7687
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.7647
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.7608
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.7571
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.7536
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.7502
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.7469
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.7438
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.7408
Epo

In [ ]:
model.get_weights()

In [ ]:
model.predict(np.array([[-0.34758084,  0.34050261]]))

In [ ]:
model.predict(np.array([[-1.05602587, -1.70251306]]))
       

In [ ]:
model.predict(np.array([[ 1.6449208 ,  0.85125653]]))

In [ ]:
model.predict(np.array([[-0.24131409,  0.51075392]]))

## forward propagation   

In [ ]:
def sigmoid(z):
    return (1/(1+np.exp(-z)))

In [ ]:
def dense(a_in,w,b):
    units=w.shape[1]
    a_out=np.zeros(units)
    for i in range(units):
        z=np.dot(w[:,i],a_in)+b[i]
        a_out[i]=sigmoid(z)
    return a_out

In [ ]:
def sequential(x,w1,b1,w2,b2):
    a_1=dense(x,w1,b1)
    a_2=dense(a_1,w2,b2)
    return a_2

In [ ]:
def predict(x,w1,b1,w2,b2):
    res=sequential(x,w1,b1,w2,b2)
    if res>=0.5:
        return 1
    else:
        return 0

In [ ]:
w1=np.array([[ 3.9579391, -4.034256 ],
        [-4.0585375,  4.3953776]])

b1=np.array([ 0.01341179, -0.00776744])

In [ ]:
w2=np.array([[-6.2692986],
        [ 3.6812208]])

b2=np.array([1.315409])

In [ ]:
predict(x[0],w1,b1,w2,b2)

In [ ]:
predict(x[1],w1,b1,w2,b2)

In [ ]:
predict(x[2],w1,b1,w2,b2)

In [ ]:
predict(x[3],w1,b1,w2,b2)