In [237]:
3+6

9

In [238]:
from tensorflow.keras.datasets import mnist
import numpy as np

In [239]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [240]:
x_train.shape

(60000, 28, 28)

In [241]:
x_train=x_train.reshape(x_train.shape[0],-1)

In [242]:
x_train.shape

(60000, 784)

In [243]:
y_train.shape

(60000,)

In [244]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [245]:
m=len(y_train)
y=np.array([np.zeros(10)]*m)
y
for i in range(m):
    res=np.zeros(10)
    ind=y_train[i]
    res[ind]=1
    y[i]=np.array(res)

y[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [246]:
x_test.shape

(10000, 28, 28)

In [247]:
y_test.shape

(10000,)

In [248]:
import tensorflow as tf

In [249]:
from tensorflow.keras.layers import Dense,Input, Flatten
from tensorflow.keras.activations import sigmoid
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.models import Sequential

In [250]:
layer_1=Dense(units=100,activation='sigmoid',input_shape=(784,))

In [251]:
layer_2=Dense(units=50,activation='sigmoid')

In [252]:
layer_3=Dense(units=10,activation='sigmoid')

In [253]:
model=Sequential([layer_1,layer_2,layer_3])

In [254]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_21 (Dense)                     │ (None, 100)                 │          78,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_22 (Dense)                     │ (None, 50)                  │           5,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_23 (Dense)                     │ (None, 10)                  │             510 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 84,060 (328.36 KB)

 Trainable params: 84,060 (328.36 KB)

 Non-trainable params: 0 (0.00 B)

In [255]:
model.compile(loss = BinaryCrossentropy,
             optimizer=tf.keras.optimizers.Adam(learning_rate=0.01))

In [256]:
x_train=x_train/255.0
x_test=x_test/255.0
x_test.shape
x_test=x_test.reshape(x_test.shape[0],-1)
x_test.shape

(10000, 784)

In [257]:
model.fit(x_train,y,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.1048
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0259
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0205
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0183
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0166


In [259]:
w1,b1=model.get_layer('dense_21').get_weights()
w1.shape

(784, 100)

In [265]:
b1.shape

(100,)

In [260]:
w2,b2=model.get_layer('dense_22').get_weights()

In [263]:
w2.shape

(100, 50)

In [264]:
b2.shape

(50,)

In [261]:
w3,b3=model.get_layer('dense_23').get_weights()

In [262]:
w3.shape

(50, 10)

In [266]:
b3.shape

(10,)

In [267]:
def sigmoid(z):
    z = np.clip(z, -500, 500)
    return 1/(1+np.exp(-z))

In [268]:
def dense(a,w,b):
    units=w.shape[1]
    z=np.dot(a,w)+b
    a_out=sigmoid(z)
    return a_out

In [269]:
def sequential(x,w1,b1,w2,b2,w3,b3):
    a1=dense(x,w1,b1)
    a2=dense(a1,w2,b2)
    a3=dense(a2,w3,b3)
    return a3

In [270]:
def predict(x,w1,b1,w2,b2,w3,b3):
    m=len(x)
    pred=np.array([np.zeros(10)]*m)
    for i in range(m):
        pred[i]=sequential(x[i],w1,b1,w2,b2,w3,b3)
    return pred

In [279]:
x_test.shape

(10000, 784)

In [293]:
res=predict(x_test,w1,b1,w2,b2,w3,b3)

In [294]:
res

array([[3.21219849e-05, 1.11346046e-04, 2.67491773e-04, ...,
        9.99806751e-01, 4.81521709e-05, 5.22584134e-05],
       [1.07209614e-03, 2.12000403e-03, 9.99123658e-01, ...,
        6.04409528e-06, 1.92697099e-04, 2.30177023e-09],
       [4.76097690e-06, 9.99314292e-01, 2.15921700e-04, ...,
        1.32368205e-04, 2.63221301e-05, 2.30560461e-07],
       ...,
       [7.78764803e-06, 3.07269848e-06, 9.37912755e-04, ...,
        2.85593870e-04, 1.07972511e-03, 9.83143210e-04],
       [1.45160695e-04, 2.90823882e-06, 1.83681529e-06, ...,
        1.34236076e-06, 1.64310596e-03, 2.04711007e-05],
       [3.54923991e-04, 3.69475145e-06, 1.36488091e-05, ...,
        5.32777794e-06, 1.41146368e-04, 2.92046655e-07]])

In [295]:
m=len(res)
n=10
for i in range(m):
    for j in range(n):
        if res[i][j]>=0.5:
            res[i][j]=1
        else:
            res[i][j]=0

res

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [296]:
m=len(y_test)
y=np.array([np.zeros(10)]*m)
y
for i in range(m):
    res=np.zeros(10)
    ind=y_test[i]
    res[ind]=1
    y[i]=np.array(res)

y

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [297]:
np.argmax(y[0]),np.argmax(y[1])   # argmax gives index where element is zero

(np.int64(7), np.int64(2))

In [298]:
def accuracy(res,y):
    count=0
    for i in range(len(res)):
        if np.argmax(res[i])!=np.argmax(y[i]):
            count+=1
        else:
            pass
    return count

In [299]:
accuracy(res,y)

9