In [84]:
import numpy as np
import time

a = np.arange(1e6)
b = np.arange(1e6)

# Loop version
start = time.time()
c = [a[i] + b[i] for i in range(len(a))]
print("Loop:", time.time() - start)

# Vectorized
start = time.time()
c = a + b
print("Vectorized:", time.time() - start)


Loop: 0.3039264678955078
Vectorized: 0.009629487991333008


In [85]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [86]:
arr.reshape((2,5)).T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [87]:
import pandas as pd

In [88]:
x = np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35],[6400,3,5,120],[3500,2,4,70],[5200,3,4,98]])

In [89]:
y=np.array([460,232,178,1000,600,800])

In [90]:
x

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [ 852,    2,    1,   35],
       [6400,    3,    5,  120],
       [3500,    2,    4,   70],
       [5200,    3,    4,   98]])

In [91]:
y

array([ 460,  232,  178, 1000,  600,  800])

In [105]:
#evaluation

def pred(w,b,x):
    res=np.dot(w,x)+b
    return res

In [106]:

def dJ_dwk(w,b,x,y,k):
    res=0
    for i in range(len(x)):
        res+= (pred(w,b,x[i])-y[i])*x[i][k]
    return res/len(x)

In [107]:
def dJ_db(w,b,x,y):
    res=0
    for i in range(len(x)):
        res+=(pred(w,b,x[i])-y[i])
    return res/len(x)

In [108]:
def cost(w,b,x,y):
    m=len(x)
    cost=0
    for i in range(m):
        cost+= (pred(w,b,x[i])-y[i])**2
    return (1/(2*m))*(cost)

In [109]:
alpha=0.1
def gradient_descent(w,b,x,y,alpha,init_cost):
    if init_cost is None:
        init_cost=cost(w,b,x,y)
    for i in range(len(w)):
        w[i]=w[i]-(alpha)*(dJ_dwk(w,b,x,y,i))
    b=b-(alpha)*(dJ_db(w,b,x,y))
    new_cost=cost(w,b,x,y)
    if new_cost<init_cost:
        init_cost=new_cost
        return gradient_descent(w,b,x,y,alpha,init_cost)
    else:
        return w,b

In [110]:
w=np.zeros(4)
b=0
result=gradient_descent(w,b,x,y,alpha,init_cost)

In [111]:
result

(array([ 2.35133467e+05, -2.28361457e+08, -1.01775107e+08,  3.53748989e+08]),
 -2384457000.0755916)

In [112]:
x_test=np.array([2104,5,1,45])
w=result[0]
y_test=np.dot(w,x_test)+result[1]

In [113]:
y_test

12785385921.127106