In [154]:
import numpy as np
import matplotlib.pyplot as plt
import math
import tensorflow as tf
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

In [121]:
x= np.array([[1.0], [2.0]])          
y = np.array([[300.0], [500.0]])

In [122]:
lin_model=LinearRegression()
lin_model.fit(x,y)

LinearRegression()

In [123]:
lin_model.coef_

array([[200.]])

In [124]:
lin_model.intercept_

array([100.])

In [125]:
linear_layer= tf.keras.layers.Dense(units=1,activation='linear')

In [126]:
linear_layer.get_weights()

[]

In [127]:
a1=linear_layer(x[0].reshape(1,1))

In [128]:
print(a1)

tf.Tensor([[-0.911729]], shape=(1, 1), dtype=float32)


In [129]:
linear_layer.get_weights()

[array([[-0.911729]], dtype=float32), array([0.], dtype=float32)]

In [130]:
w=np.array([[200]])
b=np.array([100])
linear_layer.set_weights([w,b])

In [131]:
a1=linear_layer(x[0].reshape(1,1))

In [132]:
print(a1)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)


In [133]:
linear_layer.get_weights()

[array([[200.]], dtype=float32), array([100.], dtype=float32)]

In [134]:
x = np.array([0., 1, 2, 3, 4, 5]).reshape(6,1)
y= np.array([0,  0, 0, 1, 1, 1])

In [135]:
from tensorflow.keras.models import Sequential

In [136]:
logistic_model=LogisticRegression()

In [137]:
logistic_model.fit(x,y)

LogisticRegression()

In [138]:
logistic_model.coef_

array([[1.12061113]])

In [139]:
logistic_model.intercept_

array([-2.80179296])

In [140]:
log_layer= Sequential(
    [
    tf.keras.layers.Dense(1,input_dim=1,activation='sigmoid',name='L1')
    ])

C:\Users\varad\AppData\Roaming\Python\Python310\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [141]:
log_layer.get_weights()

[array([[-0.87694347]], dtype=float32), array([0.], dtype=float32)]

In [142]:
w=np.array([[1.12061113]])
b=np.array([-2.80179296])

In [143]:
log_layer.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ L1 (Dense)                           │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [144]:
log_layer.get_layer('L1')

<Dense name=L1, built=True>

In [145]:
log_layer.get_layer('L1').get_weights()

[array([[-0.87694347]], dtype=float32), array([0.], dtype=float32)]

In [147]:
set_w=np.array([[1.12061113]])
set_b=np.array([-2.80179296])
log_layer.get_layer('L1').set_weights([set_w,set_b])

In [149]:
log_layer.get_layer('L1').get_weights()

[array([[1.1206111]], dtype=float32), array([-2.8017929], dtype=float32)]

In [150]:
a1=log_layer.predict(x[0].reshape(1,1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step


In [151]:
print(a1)

[[0.05722737]]


In [159]:
def sigmoid(w,x,b):
    return (1/(1+math.exp(-1*(np.dot(w,x)+b))))

In [160]:
sigmoid(set_w,x[0].reshape(1,1),set_b)

C:\Users\varad\AppData\Local\Temp\ipykernel_4844\402757446.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return (1/(1+math.exp(-1*(np.dot(w,x)+b))))


0.057227364585713786