In [14]:
import numpy as np
import math
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input 
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.models import Sequential
from tensorflow.keras.activations import softmax,relu

In [33]:
x = np.array([
    [1.0, 2.0],    # Class 0
    [1.5, 1.8],    # Class 0
    [5.8, 8.0],    # Class 1
    [6.0, 9.0],    # Class 1
    [8.0, 1.0],    # Class 2
    [9.0, 2.5]     # Class 2
])

y = np.array([
    0,0,1,1,2,2
])


# Method one without caring for round off errors

In [34]:
model=Sequential([
    Input(shape=(2,)),
    Dense(units=10,activation='relu'),
    Dense(units=5,activation='relu'),
    Dense(units=3,activation='softmax')
])

In [35]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                     │ (None, 10)                  │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 5)                   │              55 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 3)                   │              18 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 103 (412.00 B)

 Trainable params: 103 (412.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.compile(loss=SparseCategoricalCrossentropy)

In [37]:
model.fit(x,y,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 501ms/step - loss: 1.4347
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 1.4052
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1.3763
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.3535
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 1.3357
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 1.3188
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.3031
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.2898
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.2756
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1.2633
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.2512
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.2388
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1.2283
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 1.2168
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1.2058
Epoch 16/100
1/1 ━

In [39]:
model.get_layer('dense_15').get_weights()

[array([[-0.45132124, -0.15978238,  0.13594753, -0.28289014,  0.26447633,
         -0.5480101 , -0.03715801, -0.05270547,  0.5699062 ,  0.39538696],
        [ 0.09273523,  0.57191163, -0.5375666 , -0.48357373,  0.17897782,
          0.562735  , -0.5761455 , -0.5319079 , -0.18237428, -0.28960255]],
       dtype=float32),
 array([ 0.        ,  0.05087487, -0.08758526,  0.        ,  0.02860423,
         0.10718891,  0.        ,  0.        , -0.0887696 , -0.07586026],
       dtype=float32)]

In [40]:
model.get_layer('dense_16').get_weights()

[array([[ 0.08436668, -0.44333774,  0.42507857,  0.628393  , -0.02816999],
        [ 0.4923066 ,  0.42395982,  0.5730745 ,  0.05709483,  0.10145183],
        [ 0.47472596,  0.51438016,  0.1585392 , -0.5016259 ,  0.5356824 ],
        [-0.37514758, -0.30122378,  0.45610207, -0.12651092, -0.4681237 ],
        [ 0.28667003, -0.20699978, -0.4362972 ,  0.20440115,  0.09053955],
        [ 0.06983689, -0.36135712,  0.53018147, -0.00078929, -0.39888614],
        [-0.09437168, -0.21050948, -0.30393332,  0.05419046,  0.29341877],
        [-0.55837387,  0.08413053,  0.1267339 , -0.22390938,  0.5342577 ],
        [-0.24894513,  0.49524817,  0.583375  , -0.58794147, -0.06894425],
        [ 0.05579904, -0.0140558 , -0.5968301 , -0.4425356 , -0.4846431 ]],
       dtype=float32),
 array([ 0.02104113, -0.11130223,  0.08687297,  0.0928013 ,  0.04144424],
       dtype=float32)]

In [41]:
model.get_layer('dense_17').get_weights()

[array([[-0.12927744, -0.10433111, -0.4885451 ],
        [-0.4610767 ,  0.6251859 ,  0.24381441],
        [ 0.70254606,  0.8730093 ,  0.12173393],
        [ 0.1906307 , -0.8062072 ,  0.7231632 ],
        [-0.47250667, -0.7461559 , -0.56554437]], dtype=float32),
 array([ 0.11361194, -0.11079331,  0.10886277], dtype=float32)]

In [42]:
sample = np.array([[6.2, 8.5]])
model.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[0.14724433, 0.8242635 , 0.02849221]], dtype=float32)

In [43]:
sample = np.array([[1.5, 1.8]])
model.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[0.36741298, 0.3940006 , 0.23858644]], dtype=float32)

In [44]:
sample = np.array([[5.8, 8.0]])
model.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[0.16420887, 0.8017453 , 0.03404582]], dtype=float32)

# Method two caring for round off errors...use from_logits=True

In [45]:
model=Sequential([
    Input(shape=(2,)),
    Dense(units=10,activation='relu'),
    Dense(units=5,activation='relu'),
    Dense(units=3,activation='linear')
])

In [46]:
model.compile(loss=SparseCategoricalCrossentropy(from_logits=True))

In [47]:
model.fit(x,y,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 397ms/step - loss: 2.5818
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.4619
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.3798
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.3137
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 2.2566
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 2.2056
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.1591
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 2.1160
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.0752
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 2.0349
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 1.9971
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 1.9612
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.9276
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.8992
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1.8721
Epoch 16/100
1/1 ━

In [48]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                     │ (None, 10)                  │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 5)                   │              55 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_20 (Dense)                     │ (None, 3)                   │              18 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 208 (836.00 B)

 Trainable params: 103 (412.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 105 (424.00 B)

In [49]:
model.get_layer('dense_18').get_weights()

[array([[ 0.6799342 ,  0.02194703,  0.61185664,  0.47622037,  0.23500985,
         -0.6034299 ,  0.312562  ,  0.16396315,  0.5733104 ,  0.40077713],
        [ 0.56535906, -0.622765  ,  0.11616864,  0.01746716,  0.72355264,
         -0.0667938 , -0.50953823,  0.1304184 ,  0.41337517,  0.19300595]],
       dtype=float32),
 array([ 0.10387044,  0.        , -0.1125185 , -0.11085662,  0.02754   ,
         0.        , -0.10090756, -0.10410337, -0.07854214, -0.03158402],
       dtype=float32)]

In [50]:
model.get_layer('dense_19').get_weights()

[array([[-0.07570004, -0.29209754, -0.18612117,  0.5139115 ,  0.4510763 ],
        [-0.486911  , -0.52305305,  0.13033372, -0.37250093,  0.51523155],
        [-0.6020715 , -0.10062741,  0.4963172 , -0.1347329 , -0.36776125],
        [-0.3243078 ,  0.44497764, -0.39871937,  0.69351315, -0.55111927],
        [-0.29887313,  0.48003033, -0.44471338,  0.4417086 ,  0.18661956],
        [-0.03862375, -0.44912893, -0.20707181, -0.32956657,  0.08880711],
        [ 0.6093754 ,  0.26371172,  0.14474475, -0.04521276,  0.5049389 ],
        [-0.52055794,  0.41063806,  0.21388322, -0.26993287, -0.5867706 ],
        [ 0.44844168,  0.46134055, -0.5688394 ,  0.29367054, -0.02896376],
        [-0.38799584, -0.38443887,  0.54892653, -0.152102  , -0.21780889]],
       dtype=float32),
 array([ 0.        , -0.01964688,  0.        , -0.00510071,  0.09049898],
       dtype=float32)]

In [51]:
model.get_layer('dense_20').get_weights()

[array([[-0.03040141, -0.48743102, -0.1105271 ],
        [ 0.10011822,  0.29595277, -0.6207392 ],
        [-0.11517406,  0.82716304,  0.7564879 ],
        [ 0.06496374,  0.18738057,  0.5189432 ],
        [ 0.7504672 , -0.4325723 , -0.14668526]], dtype=float32),
 array([ 0.07420351, -0.10439391,  0.00205805], dtype=float32)]

In [61]:
sample = np.array([[6.2, 8.5]])
np.argmax(tf.nn.softmax(model.predict(sample)).numpy())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


np.int64(1)

In [62]:
sample = np.array([[1.5, 1.8]])
np.argmax(tf.nn.softmax(model.predict(sample)).numpy())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


np.int64(2)

In [63]:
sample = np.array([[5.8, 8.0]])
np.argmax(tf.nn.softmax(model.predict(sample)).numpy())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


np.int64(1)

In [65]:
sample=np.array([[6.0,9.0]])
np.argmax(tf.nn.softmax(model.predict(sample)).numpy())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


np.int64(1)

In [66]:
sample=np.array([[1.0,2.0]])
np.argmax(tf.nn.softmax(model.predict(sample)).numpy())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


np.int64(0)

In [67]:
sample=np.array([[9.0,2.5]])
np.argmax(tf.nn.softmax(model.predict(sample)).numpy())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


np.int64(1)

In [68]:
sample=np.array([[8.0,1.0]])
np.argmax(tf.nn.softmax(model.predict(sample)).numpy())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


np.int64(1)

# SparseCategoricalCrossentropy vs CategoricalCrossEntropy

if labels are directly in the name of class i.e 
y=[1,0,2,3,0] use SparsecategoricalCrossentropy

if labels are in the form of one hot encoders i.e y=[[0,1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1],[1,0,0,0]] use CtegoricalCrossEntropy